name: Deploy to WordPress.org

env:
  COMPOSER_VERSION: '2'
  COMPOSER_CACHE: '${{ github.workspace }}/.composer-cache'

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Cache Directories
        run: |
          composer config -g cache-dir "${{ env.COMPOSER_CACHE }}"

      - name: Prepare Composer Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.COMPOSER_CACHE }}
          key: composer-${{ env.COMPOSER_VERSION }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ env.COMPOSER_VERSION }}-

      - name: Set PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer:v2

      - name: Setup Node.js and install dependencies
        uses: ./.github/setup-node

      - name: Run Production Task
        run: npm run production

      - name: WordPress Plugin Deploy
        uses: nk-o/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SOURCE_DIR: dist/visual-portfolio/
          SLUG: visual-portfolio
