name: End-to-End Tests

on:
  pull_request:
  push:
    branches:
      - master
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  playwright:
    name: Playwright
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'nk-crew/visual-portfolio' || github.event_name == 'pull_request' }}
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/setup-node

      - name: Npm build
        run: npm run build

      - name: Install Playwright dependencies
        run: |
          npx playwright install chromium firefox webkit --with-deps

      - name: Install WordPress and start the server
        run: |
          npm run wp-env start

      - name: Run the tests
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test:e2e

      - name: Archive debug artifacts (screenshots, traces)
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        if: ${{ !cancelled() }}
        with:
            name: failures-artifacts--${{ matrix.part }}
            path: artifacts/test-results
            if-no-files-found: ignore

      - name: Archive flaky tests report
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        if: ${{ !cancelled() }}
        with:
            name: flaky-tests-report--${{ matrix.part }}
            path: flaky-tests
            if-no-files-found: ignore

  merge-artifacts:
    name: Merge Artifacts
    if: ${{ !cancelled() }}
    needs: [playwright]
    runs-on: ubuntu-latest
    outputs:
        has-flaky-test-report: ${{ !!steps.merge-flaky-tests-reports.outputs.artifact-id }}
    steps:
        - name: Merge failures artifacts
          uses: actions/upload-artifact/merge@v4
          # Don't fail the job if there aren't any artifacts to merge.
          continue-on-error: true
          with:
              name: failures-artifacts
              # Retain the merged artifacts in case of a rerun.
              pattern: failures-artifacts*
              delete-merged: true

        - name: Merge flaky tests reports
          id: merge-flaky-tests-reports
          uses: actions/upload-artifact/merge@v4
          continue-on-error: true
          with:
              name: flaky-tests-report
              pattern: flaky-tests-report*
              delete-merged: true
